name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]  # Include both main and master branch names
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Install dependencies
        run: cd governance-app && pnpm install --frozen-lockfile
      
      - name: Lint
        run: cd governance-app && pnpm lint
        
      - name: Build
        run: cd governance-app && pnpm build
        env:
          VITE_LANGFLOW_API_KEY: ${{ secrets.VITE_LANGFLOW_API_KEY }}
      
      - name: Prepare dist directory for GitHub Pages
        run: |
          cd governance-app
          cp public/404.html dist/
          cp public/_redirects dist/
          touch dist/.nojekyll
          # No CNAME file, we're using GitHub Pages with subdirectory
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./governance-app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
